// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_alcohol_is_dangerous_to_health = "CgkI2pWb-7ofEAIQBQ"; // <GPGSID>
        public const string achievement_we_dont_insult_mothers = "CgkI2pWb-7ofEAIQCg"; // <GPGSID>
        public const string achievement_hitman = "CgkI2pWb-7ofEAIQAw"; // <GPGSID>
        public const string achievement_speedrun = "CgkI2pWb-7ofEAIQDg"; // <GPGSID>
        public const string achievement_insulting = "CgkI2pWb-7ofEAIQBg"; // <GPGSID>
        public const string achievement_routine_of_the_restaurant = "CgkI2pWb-7ofEAIQCQ"; // <GPGSID>
        public const string achievement_patience = "CgkI2pWb-7ofEAIQDQ"; // <GPGSID>
        public const string achievement_promotion = "CgkI2pWb-7ofEAIQBA"; // <GPGSID>
        public const string achievement_none_respect = "CgkI2pWb-7ofEAIQBw"; // <GPGSID>
        public const string achievement_tourist = "CgkI2pWb-7ofEAIQDA"; // <GPGSID>
        public const string achievement_bastard = "CgkI2pWb-7ofEAIQCA"; // <GPGSID>
        public const string achievement_poison_of_patience = "CgkI2pWb-7ofEAIQCw"; // <GPGSID>
        public const string achievement_magicdeath = "CgkI2pWb-7ofEAIQAQ"; // <GPGSID>
        public const string achievement_first = "CgkI2pWb-7ofEAIQAg"; // <GPGSID>

}

